name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.11
      with:
        name: mbrandau/url-shortener
        username: mbrandau
        password: ${{secrets.DOCKER_PASSWORD}}

